// <auto-generated />
namespace CoachUs.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Create_UserDetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_UserDetails));
        
        string IMigrationMetadata.Id
        {
            get { return "201606072339344_Create_UserDetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
