// <auto-generated />
namespace CoachUs.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Set_Enums : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Set_Enums));
        
        string IMigrationMetadata.Id
        {
            get { return "201605062303253_Set_Enums"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
