//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachUs.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public Action()
        {
            this.ChildActions = new HashSet<Action>();
            this.Permissions = new HashSet<Permission>();
        }
    
        public int ID { get; set; }
        public int ParentActionID { get; set; }
        public string Name { get; set; }
        public byte Type { get; set; }
    
        public virtual ICollection<Action> ChildActions { get; set; }
        public virtual Action ParentAction { get; set; }
        public virtual ICollection<Permission> Permissions { get; set; }
    }
}
