//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachUs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityResult
    {
        public int ID { get; set; }
        public int ActivityID { get; set; }
        public byte Serie { get; set; }
        public decimal Repetition { get; set; }
        public decimal Result { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Activity Activity { get; set; }
    }
}
