//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachUs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public Activity()
        {
            this.ActivityResults = new HashSet<ActivityResult>();
        }
    
        public int ID { get; set; }
        public int TrainingID { get; set; }
        public int ActivityCategoryId { get; set; }
        public byte Order { get; set; }
        public byte Series { get; set; }
        public decimal Repetitions { get; set; }
        public byte Unit { get; set; }
        public decimal Goal { get; set; }
        public byte GoalUnit { get; set; }
        public string Notes { get; set; }
        public byte Status { get; set; }
    
        public virtual Training Training { get; set; }
        public virtual ActivityCategory ActivityCategory { get; set; }
        public virtual ICollection<ActivityResult> ActivityResults { get; set; }
    }
}
