//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachUs.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.EventTrainings = new HashSet<EventTraining>();
            this.Files = new HashSet<File>();
        }
    
        public int ID { get; set; }
        public int TeamID { get; set; }
        public System.DateTime Date { get; set; }
        public string Title { get; set; }
        public string Detail { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual ICollection<EventTraining> EventTrainings { get; set; }
        public virtual ICollection<File> Files { get; set; }
    }
}
