//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachUs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTraining
    {
        public int EventID { get; set; }
        public int TrainingID { get; set; }
        public byte Status { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Training Training { get; set; }
    }
}
