//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachUs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fare
    {
        public int ID { get; set; }
        public int TeamID { get; set; }
        public string Name { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
