//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachUs.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public Inventory()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int ID { get; set; }
        public int TeamID { get; set; }
        public string Item { get; set; }
        public string Description { get; set; }
        public int Qty { get; set; }
        public decimal Price { get; set; }
        public bool AllowCouchSell { get; set; }
        public bool AllowCouchChangePrice { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
