//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachUs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class License
    {
        public License()
        {
            this.LicensePayments = new HashSet<LicensePayment>();
        }
    
        public int ID { get; set; }
        public int OwnerID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public short TrialDays { get; set; }
        public short Days { get; set; }
        public short TotalUsers { get; set; }
        public short AvailableUsers { get; set; }
    
        public virtual ICollection<LicensePayment> LicensePayments { get; set; }
        public virtual User User { get; set; }
    }
}
