//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachUs.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicensePayment
    {
        public int ID { get; set; }
        public int LicenseID { get; set; }
        public System.DateTime Date { get; set; }
        public short Users { get; set; }
        public short Days { get; set; }
        public decimal Amount { get; set; }
        public bool IsPaid { get; set; }
    
        public virtual License License { get; set; }
    }
}
