//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachUs.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int ID { get; set; }
        public int RoleID { get; set; }
        public byte AccessType { get; set; }
        public int ActionID { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Role Role { get; set; }
    }
}
