//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachUs.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int ID { get; set; }
        public int SellerID { get; set; }
        public int BuyerID { get; set; }
        public int ItemID { get; set; }
        public decimal Price { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
