//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachUs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionPayment
    {
        public int ID { get; set; }
        public int SubscriptionID { get; set; }
        public int Amount { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Subscription Subscription { get; set; }
    }
}
