//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachUs.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.Events = new HashSet<Event>();
            this.Fares = new HashSet<Fare>();
            this.Inventories = new HashSet<Inventory>();
            this.Subscriptions = new HashSet<Subscription>();
            this.TeamPlans = new HashSet<TeamPlan>();
            this.TeamUsers = new HashSet<TeamUser>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public byte Sport { get; set; }
        public string Email { get; set; }
        public int TeamOwnerID { get; set; }
        public Nullable<int> LogoID { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<Fare> Fares { get; set; }
        public virtual File File { get; set; }
        public virtual ICollection<Inventory> Inventories { get; set; }
        public virtual ICollection<Subscription> Subscriptions { get; set; }
        public virtual ICollection<TeamPlan> TeamPlans { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<TeamUser> TeamUsers { get; set; }
    }
}
